# Generated by Django 4.1.1 on 2022-09-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=300)),
                ('apellidos', models.CharField(max_length=300)),
                ('dni', models.IntegerField(max_length=8)),
                ('telefono', models.IntegerField(max_length=9)),
                ('direccion', models.CharField(max_length=300)),
                ('fecha_nacimiento', models.DateField(verbose_name='date published')),
                ('fecha_publicacion', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
